root: true
env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:jsx-a11y/recommended
  - plugin:prettier/recommended
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
settings:
  import/resolver:
    typescript: {}
plugins:
  - react
  - '@typescript-eslint'
  - import
  - react-hooks
  - jsx-a11y
  - prettier
rules:
  import/no-default-export: error
  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
        - parent
        - sibling
        - index
        - object
      newlines-between: always
      alphabetize:
        order: asc
        caseInsensitive: true
  linebreak-style:
    - off
    - windows
  react/react-in-jsx-scope: off
  react/prop-types: error
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: error
  jsx-a11y/anchor-is-valid: off
  '@typescript-eslint/no-unused-vars':
    - error
  '@typescript-eslint/explicit-function-return-type':
    - off
  '@typescript-eslint/no-empty-function':
    - off
  '@typescript-eslint/no-explicit-any':
    - error
  prettier/prettier:
    - error
    - {}
    - usePrettierrc: true
